vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "eu-central-1b"
env_prefix = "dev"
my_ip = "x.x.x.x/32"
instance_type = "t2.micro"
public_key_location = "~/.ssh/id_rsa.pub"